# Generated by Django 3.1 on 2020-08-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='temprature',
        ),
    ]
