# Generated by Django 3.1 on 2020-08-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_city_temprature'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
