# Generated by Django 3.1 on 2020-09-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='temp',
        ),
        migrations.AddField(
            model_name='city',
            name='cityid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='ctemp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='flag',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='ftemp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
